modLoader="javafml"
loaderVersion="[4,)"
license="Not specified"

[[mods]]
modId="locodeco"
version="1.0.0"
displayName="locodeco"
displayURL="https://mcreator.net"
credits="LocoMetal Blocks \"steam n rails\""
authors="darkossbr"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.locodeco]]
    modId="neoforge"
    type="required"
    versionRange="[21.1.92,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.locodeco]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.1]"
    ordering="AFTER"
    side="BOTH"


[[dependencies.locodeco]]
    modId="create"
    type="optional"
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"


# Start of user code block dependencies configuration
# End of user code block dependencies configuration